version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: recruitment_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: recruitment
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: recruitment_adminer
    restart: always
    ports:
      - "8080:8080"
